#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#python'
enable = true

[[layers]]
name = 'lang#c'
enable = true
format_on_save = false
enable_clang_syntax_highlight = true

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'fzf'

[[custom_plugins]]
name = 'ryanoasis/vim-devicons'
merged = 0

[options]
colorscheme = 'onedark'
colorscheme_bg = 'dark'
statusline_separator = "arrow"
statusline_iseparator = "arrow"
enable_tabline_filetype_icon = true
enable_statusline_mode = true
enable_guicolors = false 
wrap_line = true
buffer_index_type = 4
escape_key_binding = 'fj'
enable_ycm = true 
enable_statusline_bfpath = true
bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'
